import { Inter } from "next/font/google";
import "./style/globals.css";
import Header from "./layout/Header";
import Footer from "./layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className= " flex flex-col justify-between h-screen">
        <div className="box">
        <Header/>
        <main className="w-full h-screen text-center align-middle bg-primary">
        {children}
        </main>
        </div>
        <Footer/>
        </body>
    </html>
  );
}
